# Generated by Django 4.1.1 on 2022-09-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='host_id',
            new_name='host',
        ),
    ]
